version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/flowable-ci # directory where steps will run

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: flowable-ci-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: flowable-ci-{{ checksum "pom.xml" }}
      
      - run: mvn clean package -Pcheck
      
      - store_test_results:
          path: target/surefire-reports
