version: 2.1
jobs:
  build:
    # working_directory: ~/flowable

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:
      - checkout
          # path: checkout

      - restore_cache:
          key: flowable-qa-{{ checksum "pom.xml" }}

      - run: 
          name: Setup MAVEN_OPTS
          command: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"
      
      - run: 
          name: Caching dependencies
          command: mvn -s .circleci/settings.xml de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -Pcheck -Dmaven.repo.local=~/.m2/repository
      
      - save_cache:
          paths:
            - ~/.m2
          key: flowable-qa-{{ checksum "pom.xml" }}

  qa_postgres:
    working_directory: ~/flowable

    docker:
      - image: circleci/openjdk:8u171-jdk

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: flowable
          POSTGRES_DB: flowable
          POSTGRES_PASSWORD: flowable

    steps:
      # - attach_workspace:
      #     at: ~/flowable
      - checkout

      - restore_cache:
          key: flowable-qa-{{ checksum "pom.xml" }}

      - run: 
          name: Setup MAVEN_OPTS
          command: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"

      - run:
          name: Create db properties
          command: |
            mkdir -p ~/.flowable/jdbc
            echo "jdbc.url=jdbc:postgresql://localhost:5432/flowable" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.driver=org.postgresql.Driver" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.username=flowable" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.password=flowable" >> ~/.flowable/jdbc/build.flowable6.postgres.properties

      - run: 
          name: Run Postgres QA test
          command: mvn -s .circleci/settings.xml clean install -Ddatabase=postgres -Pcheck,errorLogging -Dmaven.repo.local=~/.m2/repository

  qa_mysql:
    working_directory: ~/flowable

    docker:
      - image: circleci/openjdk:8u171-jdk

      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=flowable
          - MYSQL_DATABASE=flowable
          - MYSQL_USER=flowable

    steps:
      # - attach_workspace:
      #     at: ~/flowable
      - checkout

      - restore_cache:
          key: flowable-qa-{{ checksum "pom.xml" }}

      - run: 
          name: Setup MAVEN_OPTS
          command: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"

      - run:
          name: Create db properties
          command: |
            mkdir -p ~/.flowable/jdbc
            echo "jdbc.url=jdbc:mysql://localhost:3306/flowable?characterEncoding=UTF-8" >> ~/.flowable/jdbc/build.flowable6.mysql.properties
            echo "jdbc.driver=com.mysql.jdbc.Driver" >> ~/.flowable/jdbc/build.flowable6.mysql.properties
            echo "jdbc.username=flowable" >> ~/.flowable/jdbc/build.flowable6.mysql.properties
            echo "jdbc.password=flowable" >> ~/.flowable/jdbc/build.flowable6.mysql.properties

      - run: 
          name: Run MySQL QA test
          command: mvn -s .circleci/settings.xml clean install -Ddatabase=mysql -Pcheck,errorLogging -Dmaven.repo.local=~/.m2/repository

workflows:
  version: 2.1

  flowable_qa:
    jobs:
      - build
      - qa_postgres:
          requires:
            - build
      - qa_mysql:
          requires:
            - build