version: 2.1
jobs:
  build:
    working_directory: ~/flowable

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:
      - checkout:
          path: checkout

      - restore_cache:
          key: flowable-ci-{{ checksum "~/flowable/checkout/pom.xml" }}

      - run: 
          name: Setup MAVEN_OPTS
          command: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"
      
      - run: 
          name: Caching dependencies
          command: cd ~/flowable/checkout && mvn -s .circleci/settings.xml de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -Pcheck -Dmaven.repo.local=~/.m2/repository
      
      - save_cache:
          paths:
            - ~/.m2
          key: flowable-ci-{{ checksum "~/flowable-qa/checkout/pom.xml" }}
      
      - run: 
          name: Compile code
          command: cd ~/flowable/checkout && mvn -s .circleci/settings.xml clean install -Pcheck,errorLogging -DskipTests -Dmaven.repo.local=~/.m2/repository

      - persist_to_workspace:
          root: ~/flowable
          paths:
            - checkout

  qa_postgres:
    working_directory: ~/flowable

    docker:
      - image: circleci/openjdk:8u171-jdk

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: flowable
          POSTGRES_DB: flowable

    steps:
      - attach_workspace:
          at: ~/flowable

      - restore_cache:
          key: flowable-ci-{{ checksum "~/flowable/checkout/pom.xml" }}

      - run: 
          name: Setup MAVEN_OPTS
          command: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"

      - run:
          name: Create db properties
          command: |
            mkdir -p ~/.flowable/jdbc
            echo "jdbc.url=jdbc:postgresql://localhost:5432/flowable" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.driver=org.postgresql.Driver" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.username=flowable" >> ~/.flowable/jdbc/build.flowable6.postgres.properties
            echo "jdbc.password=" >> ~/.flowable/jdbc/build.flowable6.postgres.properties

      - run: 
          name: Run Postgres QA test
          command: cd ~/flowable/checkout && mvn -s .circleci/settings.xml clean install -Ddatabase=postgres -Pcheck,errorLogging -Dmaven.repo.local=~/.m2/repository

workflows:
  version: 2.1

  flowable_qa:
    jobs:
      - build
      - qa_postgres:
          requires:
            - build