version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/flowable-ci # directory where steps will run

    docker:
      - image: circleci/openjdk:11

    steps:

      - checkout

      # - restore_cache:
      #     key: flowable-ci-{{ checksum "pom.xml" }}

      - run: export MAVEN_OPTS="-Xmx2048m -Xms1024m -Djava.awt.headless=true"
      
      # - run: mvn de.qaware.maven:go-offline-maven-plugin:1.1.0:resolve-dependencies -Dmaven.repo.local=~/.m2/repository
      
      # - save_cache:
      #     paths:
      #       - ~/.m2
      #     key: flowable-ci-{{ checksum "pom.xml" }}
      
      - run: mvn clean test -Pcheck,errorLogging
      
      - store_test_results:
          path: target/surefire-reports
